config/routes.rb
Rails.application.routes.draw do
  get 'relationships/followings'
  get 'relationships/followers'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root to: "homes#top"
  devise_for :users
  get "home/about"=>"homes#about"
  get "search" => "searches#search"

  resources :books, only: [:index,:show,:edit,:create,:destroy,:update] do
    resource :favorites, only: [:create,:destroy]
    resources :book_comments, only: [:create,:destroy]
  end

  resources :users, only: [:index,:show,:edit,:update] do
    resource :relationships, only: [:create,:destroy]
    get 'followings' => 'relationships#followings', as: 'followings'
    get 'followers' => 'relationships#followers', as: 'followers'
  end

  resources :chats, only: [:show, :create]
  #・chats#show：チャットをやり取りするビューを返す
  #・chats#create：入力されたメッセージをデータベースに保存する



  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

end

app/models/book_comment.rb
class BookComment < ApplicationRecord

  belongs_to :user
  belongs_to :book

  validates :comment,presence:true
  
end

app/controllers/book_comments_controller.rb
class BookCommentsController < ApplicationController

  def create
    @book = Book.find(params[:book_id])
    @comment = current_user.book_comments.new(book_comments_params)
    @comment.book_id = @book.id
    @comment.save

  end

  def destroy
    @book = Book.find(params[:book_id])
    comment = BookComment.find_by(id: params[:id],book_id: params[:book_id])
    comment.destroy

  end

  private

  def book_comments_params
    params.require(:book_comment).permit(:comment)
  end
end

app/helpers/book_comments_helper.rb
module BookCommentsHelper
end

app/views/book_comments/_form.html.erb
<%= form_with model: [book,book_comment], local: false do |f| %>
       <div class="form-group">
           <%= f.text_area :comment, class: "w-100 comments-form" %>
       </div>
       <div class="form-group">
           <%= f.submit "送信" %>
       </div>
<% end %>

app/views/book_comments/_index.html.erb
<table>
   <tbody>
     <% book.book_comments.each do |book_comment| %>
          <tr>
            <td>
             <%= link_to user_path(book_comment.user) do %>
              <%= image_tag book_comment.user.get_profile_image, size:"50x50" %><br>
              <%= book_comment.user.name %>
             <% end %>
            </td>
            <td>
              <%= book_comment.comment %>
            </td>
             <% if book_comment.user == current_user %>
            <td>
              <%= link_to 'Destroy',book_book_comment_path(book,book_comment.id), method: :delete, remote: true, class: "btn btn-sm btn-danger" %>
            </td>
             <% end %>
          </tr>
     <% end %>
   </tbody>
</table>

app/views/book_comments/create.js.erb
$("#comments-index").html("<%= j(render 'book_comments/index', book: @book, comment: @comment) %>");
$(".comments-form").val('');

app/views/book_comments/destroy.js.erb
$("#comments-index").html("<%= j(render 'book_comments/index', book: @book) %>");